import os
from enum import Enum, auto


class SEProperties(Enum):
    F_P_HEADER = auto()
    F_P_FLAVOR = auto()
    F_P_RULE = auto()
    B_P_HEADER = auto()
    B_P_RULE = auto()
    F_CONNECTION = auto()
    B_CONNECTION = auto()
    SLOT = auto()
    SKILL = auto()
    DECK_HEADER = auto()
    DECK_RULE = auto()
    FACTION = auto()

class LocationIcon(StrEnum):
    TILDE = "Slash"
    SQUARE = "Square"
    PLUS = "Cross"
    CIRCLE = "Circle"
    TRIANGLE = "Triangle"
    DIAMOND = "Diamond"
    CRESCENT = "Moon"
    TEE = "T"
    APOSTROPHE = "Quote"
    CLOVER = "Clover"
    STAR = "Star"
    HEART = "Heart"
    SPADE = "Spade"
    HOURGLASS = "Hourglass"
    STAR = "Star"
    HEART = "Heart"
    SPADE = "Spade"

SE_PROPERTY_COUNTS = {
    SEProperties.F_P_HEADER: 8,
    SEProperties.F_P_FLAVOR: 8,
    SEProperties.F_P_RULE: 8,
    SEProperties.B_P_HEADER: 7,
    SEProperties.B_P_RULE: 6,
    SEProperties.F_CONNECTION: 6,
    SEProperties.B_CONNECTION: 6,
    SEProperties.SLOT: 2,
    SEProperties.SKILL: 6,
    SEProperties.DECK_HEADER: 8,
    SEProperties.DECK_RULE: 8,
    SEProperties.FACTION: 3,
}
SLOT_MAP = {
    "Hand": "1 Hand",
    "Hand x2": "2 Hands",
    "Arcane": "1 Arcane",
    "Arcane x2": "2 Arcane",
    "Ally": "Ally",
    "Body": "Body",
    "Accessory": "Accessory",
    "Tarot": "Tarot",
}
HTML_PARSER = "html.parser"
PACK_YEAR_MAP = {
    "core": "2016",
    "rcore": "2020",
    "dwl": "2016",
    "tmm": "2016",
    "tece": "2016",
    "bota": "2016",
    "uau": "2016",
    "wda": "2016",
    "litas": "2016",
    "ptc": "2017",
    "eotp": "2017",
    "tuo": "2017",
    "apot": "2017",
    "tpm": "2017",
    "bsr": "2017",
    "dca": "2017",
    "tfa": "2017",
    "tof": "2017",
    "tbb": "2017",
    "hote": "2017",
    "tcoa": "2017",
    "tdoy": "2017",
    "sha": "2017",
    "tcu": "2018",
    "tsn": "2018",
    "wos": "2018",
    "fgg": "2018",
    "uad": "2018",
    "icc": "2018",
    "bbt": "2018",
    "tde": "2019",
    "sfk": "2019",
    "tsh": "2019",
    "dsm": "2019",
    "pnr": "2019",
    "wgd": "2019",
    "woc": "2019",
    "nat": "2019",
    "har": "2019",
    "win": "2019",
    "jac": "2019",
    "ste": "2019",
    "tic": "2020",
    "itd": "2020",
    "def": "2020",
    "hhg": "2020",
    "lif": "2020",
    "lod": "2020",
    "itm": "2020",
    "eoep": "2021",
    "eoec": "2021",
    "rtnotz": "2017",
    "rtdwl": "2018",
    "rtptc": "2019",
    "rttfa": "2020",
    "rttcu": "2021",
    "cotr": "2016",
    "coh": "2016",
    "lol": "2017",
    "guardians": "2018",
    "hotel": "2019",
    "blob": "2019",
    "wog": "2020",
    "rod": "2020",
    "aon": "2020",
    "bad": "2020",
    "btb": "2021",
    "rtr": "2021",
    "hoth": "2017",
    "tdor": "2017",
    "iotv": "2017",
    "tdg": "2017",
    "tftbw": "2017",
    "bob": "2020",
    "dre": "2020",
}
SKILL_NAMES = ["willpower", "intellect", "combat", "agility", "wild"]


class AssignmentType(Enum):
    STATIC = auto()
    DYNAMIC = auto()
    RANGE = auto()


PROCESS_STEPS = ["translate", "generate", "pack", "upload", "update"]
SUPPORTED_LANGUAGES = ["es", "de", "it", "fr", "ko", "uk", "pl", "ru", "zh_TW", "zh_CN"]
SCRIPT_ARGS = {
    "lang": {"default": "zh_CN", "choices": SUPPORTED_LANGUAGES, "help": "The language to translate into"},
    "se-executable": {"default": r"C:\Program Files\StrangeEons\bin\eons.exe", "help": "The Strange Eons executable path"},
    "se-preferences": {"default": rf'{os.getenv("APPDATA")}\StrangeEons3\preferences', "help": "The Strange Eons preferences file path"},
    "filter": {"default": "True", "help": "A Python expression filter for what cards to process"},
    "repo-dir": {"default": "repos", "help": "The directory to keep intermediate repositories during processing"},
    "cache-dir": {"default": "cache", "help": "The directory to keep intermediate resources during processing"},
    "decks-dir": {"default": "decks", "help": "The directory to keep translated deck images"},
    "ahdb-dir": {"default": "repos/arkhamdb-json-data", "help": "The directory to the ArkhamDB json data repository"},
    "mod-dir-primary": {"default": "repos/SCED", "help": "The directory to the primary mod repository"},
    "mod-dir-secondary": {"default": "repos/loadable-objects", "help": "The directory to the secondary mod repository"},
    "url-file": {"default": "cache/urls.json", "help": "The file to keep the url mapping"},
    "dropbox-token": {"default": None, "help": "The dropbox token for uploading translated deck images"},
    "new-link": {"action": "store_true", "help": "Whether to create new URL while uploading deck images"},
    "step": {"default": None, "choices": PROCESS_STEPS, "help": "The particular automation step to run"}
}
REVERSED_CARD_CODES = [
    "03182b",
    "03221b",
    "03325b",
    "03326b",
    "03326d",
    "03327b",
    "03327d",
    "03327f",
    "03328b",
    "03328d",
    "03328f",
    "03329b",
    "03329d",
    "03330b",
    "03331b",
    "04325b",
    "04326b",
    "05085b",
    "05166",
    "05167",
    "05168",
    "05169",
    "05170",
    "05171",
    "05172",
    "05173",
    "05174",
    "05175",
    "05176",
    "05217",
    "05262",
    "05263",
    "05264",
    "05265",
    "07252",
    "51026b",
    "82017",
    "82018",
    "82019",
    "82020",
    "83022b",
    "83023b",
    "83024b",
    "83025b",
    "83026b",
]
ENCOUNTER_SET_TO_CARD_COUNT = {
    "torch": 16,
    "arkham": 20,
    "cultists": 5,
    "tentacles": 18,
    "rats": 3,
    "ghouls": 7,
    "striking_fear": 7,
    "ancient_evils": 3,
    "chilling_cold": 4,
    "pentagram": 6,
    "nightgaunts": 4,
    "locked_doors": 2,
    "agents_of_hastur": 4,
    "agents_of_yog": 4,
    "agents_of_shub": 4,
    "agents_of_cthulhu": 4,
    "armitages_fate": 1,
    "extracurricular_activity": 21,
    "the_house_always_wins": 23,
    "sorcery": 6,
    "bishops_thralls": 6,
    "dunwich": 4,
    "whippoorwills": 5,
    "bad_luck": 6,
    "beast_thralls": 6,
    "naomis_crew": 6,
    "the_beyond": 6,
    "hideous_abominations": 3,
    "the_miskatonic_museum": 34,
    "essex_county_express": 36,
    "blood_on_the_altar": 38,
    "undimensioned_and_unseen": 38,
    "where_doom_awaits": 32,
    "lost_in_time_and_space": 36,
    "curtain_call": 20,
    "the_last_king": 25,
    "delusions": 6,
    "byakhee": 4,
    "inhabitants_of_carcosa": 3,
    "evil_portents": 6,
    "hauntings": 4,
    "hasturs_gift": 6,
    "cult_of_the_yellow_sign": 6,
    "decay": 6,
    "stranger": 3,
    "echoes_of_the_past": 32,
    "the_unspeakable_oath": 36,
    "a_phantom_of_truth": 38,
    "the_pallid_mask": 36,
    "black_stars_rise": 38,
    "vortex": 38,
    "flood": 38,
    "dim_carcosa": 36,
    "wilds": 11,
    "eztli": 15,
    "rainforest": 11,
    "serpents": 7,
    "expedition": 5,
    "agents_of_yig": 6,
    "guardians_of_time": 4,
    "traps": 5,
    "flux": 5,
    "ruins": 7,
    "pnakotic_brotherhood": 6,
    "venom": 5,
    "poison": 6,
    "threads_of_fate": 40,
    "the_boundary_beyond": 36,
    "heart_of_the_elders": 8,
    "pillars_of_judgment": 13,
    "knyan": 13,
    "the_city_of_archives": 44,
    "the_depths_of_yoth": 36,
    "shattered_aeons": 36,
    "turn_back_time": 4,
    "disappearance_at_the_twilight_estate": 7,
    "the_witching_hour": 15,
    "at_deaths_doorstep": 21,
    "the_watcher": 3,
    "agents_of_azathoth": 4,
    "anettes_coven": 4,
    "witchcraft": 7,
    "silver_twilight_lodge": 6,
    "city_of_sins": 5,
    "spectral_predators": 5,
    "trapped_spirits": 4,
    "realm_of_death": 4,
    "inexorable_fate": 6,
    "the_secret_name": 38,
    "the_wages_of_sin": 40,
    "for_the_greater_good": 38,
    "union_and_disillusion": 42,
    "in_the_clutches_of_chaos": 22,
    "music_of_the_damned": 8,
    "secrets_of_the_universe": 8,
    "before_the_black_throne": 36,
    "beyond_the_gates_of_sleep": 25,
    "waking_nightmare": 25,
    "agents_of_atlach_nacha": 4,
    "agents_of_nyarlathotep": 4,
    "whispers_of_hypnos": 3,
    "creatures_of_the_underworld": 4,
    "dreamers_curse": 6,
    "dreamlands": 4,
    "merging_realities": 6,
    "spiders": 6,
    "corsairs": 4,
    "zoogs": 6,
    "the_search_for_kadath": 43,
    "a_thousand_shapes_of_horror": 34,
    "dark_side_of_the_moon": 37,
    "point_of_no_return": 28,
    "terror_of_the_vale": 4,
    "descent_into_the_pitch": 4,
    "where_the_gods_dwell": 41,
    "weaver_of_the_cosmos": 38,
    "the_pit_of_despair": 18,
    "the_vanishing_of_elina_harper": 28,
    "agents_of_dagon": 4,
    "agents_of_hydra": 4,
    "creatures_of_the_deep": 6,
    "rising_tide": 6,
    "fog_over_innsmouth": 3,
    "shattered_memories": 6,
    "malfunction": 2,
    "syzygy": 4,
    "flooded_caverns": 6,
    "the_locals": 6,
    "in_too_deep": 35,
    "devil_reef": 38,
    "horror_in_high_gear": 42,
    "a_light_in_the_fog": 40,
    "the_lair_of_dagon": 36,
    "into_the_maelstrom": 42,
    "ice_and_death": 21,
    "the_crash": 5,
    "lost_in_the_night": 21,
    "seeping_nightmares": 9,
    "fatal_mirage": 53,
    "to_the_forbidden_peaks": 34,
    "city_of_the_elder_things": 47,
    "the_heart_of_madness": 18,
    "the_great_seal": 14,
    "stirring_in_the_deep": 31,
    "agents_of_the_unknown": 4,
    "creatures_in_the_ice": 7,
    "deadly_weather": 6,
    "elder_things": 6,
    "hazards_of_antarctica": 5,
    "left_behind": 6,
    "nameless_horrors": 6,
    "miasma": 4,
    "penguins": 4,
    "shoggoths": 3,
    "silence_and_mystery": 5,
    "expedition_team": 9,
    "tekelili": 16,
    "memorials_of_the_lost": 9,
    "return_to_the_gathering": 16,
    "return_to_the_midnight_masks": 8,
    "return_to_the_devourer_below": 7,
    "ghouls_of_umôrdhoth": 7,
    "the_devourers_cult": 6,
    "return_cult": 3,
    "return_to_extracurricular_activities": 4,
    "return_to_the_house_always_wins": 7,
    "return_to_the_miskatonic_museum": 7,
    "return_to_the_essex_county_express": 7,
    "return_to_blood_on_the_altar": 10,
    "return_to_undimensioned_and_unseen": 7,
    "return_to_where_doom_awaits": 6,
    "return_to_lost_in_time_and_space": 8,
    "beyond_the_threshold": 6,
    "resurgent_evils": 3,
    "secret_doors": 2,
    "creeping_cold": 4,
    "erratic_fear": 7,
    "yog_sothoths_emissaries": 4,
    "return_to_curtain_call": 7,
    "return_to_the_last_king": 9,
    "return_to_echoes_of_the_past": 7,
    "return_to_the_unspeakable_oath": 6,
    "return_to_a_phantom_of_truth": 9,
    "return_to_the_pallid_mask": 6,
    "return_to_black_stars_rise": 5,
    "return_to_dim_carcosa": 6,
    "delusory_evils": 3,
    "decaying_reality": 6,
    "hasturs_envoys": 4,
    "maddening_delusions": 6,
    "neurotic_fear": 7,
    "return_to_the_untamed_wilds": 1,
    "return_to_the_doom_of_eztli": 11,
    "return_to_threads_of_fate": 10,
    "return_to_the_boundary_beyond": 7,
    "return_to_pillars_of_judgment": 4,
    "return_to_knyan": 5,
    "return_to_the_city_of_archives": 7,
    "return_to_the_depths_of_yoth": 2,
    "return_to_shattered_aeons": 6,
    "return_to_turn_back_time": 1,
    "return_to_the_rainforest": 4,
    "cult_of_pnakotus": 6,
    "doomed_expedition": 5,
    "temporal_hunters": 5,
    "venomous_hate": 5,
    "return_to_disappearance_at_the_twilight_estate": 1,
    "return_to_the_witching_hour": 7,
    "return_to_at_deaths_doorstep": 5,
    "return_to_the_secret_name": 5,
    "return_to_the_wages_of_sin": 9,
    "return_to_for_the_greater_good": 4,
    "return_to_union_and_disillusion": 4,
    "return_to_in_the_clutches_of_chaos": 7,
    "return_to_before_the_black_throne": 9,
    "hexcraft": 7,
    "impending_evils": 3,
    "unspeakable_fate": 6,
    "unstable_realm": 4,
    "city_of_the_damned": 5,
    "chilling_mists": 4,
    "bloodthirsty_spirits": 4,
    "bayou": 39,
    "rougarou": 18,
    "venice": 55,
    "in_the_labyrinths_of_lunacy": 47,
    "single_group": 13,
    "epic_multiplayer": 20,
    "the_eternal_slumber": 18,
    "the_nights_usurper": 17,
    "brotherhood_of_the_beast": 6,
    "sands_of_egypt": 33,
    "abyssal_tribute": 2,
    "abyssal_gifts": 2,
    "murder_at_the_excelsior_hotel": 53,
    "alien_interference": 5,
    "excelsior_management": 5,
    "dark_rituals": 5,
    "vile_experiments": 5,
    "sins_of_the_past": 5,
    "blob": 54,
    "blob_epic_multiplayer": 3,
    "blob_single_group": 3,
    "migo_incursion": 18,
    "war_of_the_outer_gods": 51,
    "death_of_stars": 10,
    "children_of_paradise": 10,
    "swarm_of_assimilation": 10,
    "read_or_die": 4,
    "all_or_nothing": 9,
    "bad_blood": 4,
    "by_the_book": 5,
    "red_tide_rising": 5,
    None: 0,
}
ENCOUNTER_SETS_TO_NAMES = {
    "torch": "TheGathering",
    "arkham": "TheMidnightMasks",
    "cultists": "CultOfUmordhoth",
    "tentacles": "TheDevourerBelow",
    "rats": "Rats",
    "ghouls": "Ghouls",
    "striking_fear": "StrikingFear",
    "ancient_evils": "AncientEvils",
    "chilling_cold": "ChillingCold",
    "pentagram": "DarkCult",
    "nightgaunts": "Nightgaunts",
    "locked_doors": "LockedDoors",
    "agents_of_hastur": "AgentsOfHastur",
    "agents_of_yog": "AgentsOfYogSothoth",
    "agents_of_shub": "AgentsOfShubNiggurath",
    "agents_of_cthulhu": "AgentsOfCthulhu",
    "armitages_fate": "ArmitagesFate",
    "extracurricular_activity": "ExtracurricularActivity",
    "the_house_always_wins": "TheHouseAlwaysWins",
    "sorcery": "Sorcery",
    "bishops_thralls": "BishopsThralls",
    "dunwich": "Dunwich",
    "whippoorwills": "Whippoorwills",
    "bad_luck": "BadLuck",
    "beast_thralls": "BeastThralls",
    "naomis_crew": "NaomisCrew",
    "the_beyond": "TheBeyond",
    "hideous_abominations": "HideousAbominations",
    "the_miskatonic_museum": "TheMiskatonicMuseum",
    "essex_county_express": "TheEssexCountyExpress",
    "blood_on_the_altar": "BloodOnTheAltar",
    "undimensioned_and_unseen": "UndimensionedAndUnseen",
    "where_doom_awaits": "WhereDoomAwaits",
    "lost_in_time_and_space": "LostInTimeAndSpace",
    "curtain_call": "CurtainCall",
    "the_last_king": "TheLastKing",
    "delusions": "Delusions",
    "byakhee": "Byakhee",
    "inhabitants_of_carcosa": "InhabitantsOfCarcosa",
    "evil_portents": "EvilPortents",
    "hauntings": "Hauntings",
    "hasturs_gift": "HastursGift",
    "cult_of_the_yellow_sign": "CultOfTheYellowSign",
    "decay": "DecayAndFilth",
    "stranger": "TheStranger",
    "echoes_of_the_past": "EchoesOfThePast",
    "the_unspeakable_oath": "TheUnspeakableOath",
    "a_phantom_of_truth": "APhantomOfTruth",
    "the_pallid_mask": "ThePallidMask",
    "black_stars_rise": "BlackStarsRise",
    "vortex": "TheVortexAbove",
    "flood": "TheFloodBelow",
    "dim_carcosa": "DimCarcosa",
    "wilds": "TheUntamedWilds",
    "eztli": "TheDoomOfEztli",
    "rainforest": "Rainforest",
    "serpents": "Serpents",
    "expedition": "Expedition",
    "agents_of_yig": "AgentsOfYig",
    "guardians_of_time": "GuardiansOfTime",
    "traps": "DeadlyTraps",
    "flux": "TemporalFlux",
    "ruins": "ForgottenRuins",
    "pnakotic_brotherhood": "PnakoticBrotherhood",
    "venom": "YigsVenom",
    "poison": "Poison",
    "threads_of_fate": "ThreadsOfFate",
    "the_boundary_beyond": "TheBoundaryBeyond",
    "heart_of_the_elders": "HeartOfTheElders",
    "pillars_of_judgment": "PillarsOfJudgment",
    "knyan": "KnYan",
    "the_city_of_archives": "TheCityOfArchives",
    "the_depths_of_yoth": "TheDepthsOfYoth",
    "shattered_aeons": "ShatteredAeons",
    "turn_back_time": "TurnBackTime",
    "disappearance_at_the_twilight_estate": "DisappearanceAtTheTwilightEstate",
    "the_witching_hour": "TheWitchingHour",
    "at_deaths_doorstep": "AtDeathsDoorstep",
    "the_watcher": "TheWatcher",
    "agents_of_azathoth": "AgentsOfAzathoth",
    "anettes_coven": "AnettesCoven",
    "witchcraft": "Witchcraft",
    "silver_twilight_lodge": "SilverTwilightLodge",
    "city_of_sins": "CityOfSins",
    "spectral_predators": "SpectralPredators",
    "trapped_spirits": "TrappedSpirits",
    "realm_of_death": "RealmOfDeath",
    "inexorable_fate": "InexorableFate",
    "the_secret_name": "TheSecretName",
    "the_wages_of_sin": "TheWagesOfSin",
    "for_the_greater_good": "ForTheGreaterGood",
    "union_and_disillusion": "UnionAndDisillusion",
    "in_the_clutches_of_chaos": "InTheClutchesOfChaos",
    "music_of_the_damned": "MusicOfTheDamned",
    "secrets_of_the_universe": "SecretsOfTheUniverse",
    "before_the_black_throne": "BeforeTheBlackThrone",
    "beyond_the_gates_of_sleep": "BeyondTheGatesOfSleep",
    "waking_nightmare": "WakingNightmare",
    "agents_of_atlach_nacha": "AgentsOfAtlachNacha",
    "agents_of_nyarlathotep": "AgentsOfNyarlathotep",
    "whispers_of_hypnos": "WhispersOfHypnos",
    "creatures_of_the_underworld": "CreaturesOfTheUnderworld",
    "dreamers_curse": "DreamersCurse",
    "dreamlands": "Dreamlands",
    "merging_realities": "MergingRealities",
    "spiders": "Spiders",
    "corsairs": "Corsairs",
    "zoogs": "Zoogs",
    "the_search_for_kadath": "TheSearchForKadath",
    "a_thousand_shapes_of_horror": "AThousandShapesOfHorror",
    "dark_side_of_the_moon": "DarkSideOfTheMoon",
    "point_of_no_return": "PointOfNoReturn",
    "terror_of_the_vale": "TerrorOfTheVale",
    "descent_into_the_pitch": "DescentIntoThePitch",
    "where_the_gods_dwell": "WhereTheGodsDwell",
    "weaver_of_the_cosmos": "WeaverOfTheCosmos",
    "the_pit_of_despair": "ThePitOfDespair",
    "the_vanishing_of_elina_harper": "TheVanishingOfElinaHarper",
    "agents_of_dagon": "AgentsOfDagon",
    "agents_of_hydra": "AgentsOfHydra",
    "creatures_of_the_deep": "CreaturesOfTheDeep",
    "rising_tide": "RisingTide",
    "fog_over_innsmouth": "FogOverInnsmouth",
    "shattered_memories": "ShatteredMemories",
    "malfunction": "Malfunction",
    "syzygy": "Syzygy",
    "flooded_caverns": "FloodedCaverns",
    "the_locals": "TheLocals",
    "in_too_deep": "InTooDeep",
    "devil_reef": "DevilReef",
    "horror_in_high_gear": "HorrorInHighGear",
    "a_light_in_the_fog": "ALightInTheFog",
    "the_lair_of_dagon": "TheLairOfDagon",
    "into_the_maelstrom": "IntoTheMaelstrom",
    "ice_and_death": "IceAndDeath",
    "the_crash": "TheCrash",
    "lost_in_the_night": "LostInTheNight",
    "seeping_nightmares": "SeepingNightmares",
    "fatal_mirage": "FatalMirage",
    "to_the_forbidden_peaks": "ToTheForbiddenPeaks",
    "city_of_the_elder_things": "CityOfTheElderThings",
    "the_heart_of_madness": "TheHeartOfMadness",
    "the_great_seal": "TheGreatSeal",
    "stirring_in_the_deep": "StirringInTheDeep",
    "agents_of_the_unknown": "AgentsOfTheUnknown",
    "creatures_in_the_ice": "CreaturesInTheIce",
    "deadly_weather": "DeadlyWeather",
    "elder_things": "ElderThings",
    "hazards_of_antarctica": "HazardsOfAntarctica",
    "left_behind": "LeftBehind",
    "nameless_horrors": "NamelessHorrors",
    "miasma": "Miasma",
    "penguins": "Penguins",
    "shoggoths": "Shoggoths",
    "silence_and_mystery": "SilenceAndMystery",
    "expedition_team": "ExpeditionTeam",
    "tekelili": "TekeliLi",
    "memorials_of_the_lost": "MemorialsOfTheLost",
    "return_to_the_gathering": "ReturnToTheGathering",
    "return_to_the_midnight_masks": "ReturnToTheMidnightMasks",
    "return_to_the_devourer_below": "ReturnToTheDevourerBelow",
    "ghouls_of_umôrdhoth": "GhoulsOfUmordhoth",
    "the_devourers_cult": "TheDevourersCult",
    "return_cult": "ReturnToCultOfUmordhoth",
    "return_to_extracurricular_activities": "ReturnToExtracurricularActivities",
    "return_to_the_house_always_wins": "ReturnToTheHouseAlwaysWins",
    "return_to_the_miskatonic_museum": "ReturnToTheMiskatonicMuseum",
    "return_to_the_essex_county_express": "ReturnToTheEssexCountyExpress",
    "return_to_blood_on_the_altar": "ReturnToBloodOnTheAltar",
    "return_to_undimensioned_and_unseen": "ReturnToUndimensionedAndUnseen",
    "return_to_where_doom_awaits": "ReturnToWhereDoomAwaits",
    "return_to_lost_in_time_and_space": "ReturnToLostInTimeAndSpace",
    "beyond_the_threshold": "BeyondTheThreshold",
    "resurgent_evils": "ResurgentEvils",
    "secret_doors": "SecretDoors",
    "creeping_cold": "CreepingCold",
    "erratic_fear": "ErraticFear",
    "yog_sothoths_emissaries": "YogSothothsEmissaries",
    "return_to_curtain_call": "ReturnToCurtainCall",
    "return_to_the_last_king": "ReturnToTheLastKing",
    "return_to_echoes_of_the_past": "ReturnToEchoesOfThePast",
    "return_to_the_unspeakable_oath": "ReturnToTheUnspeakableOath",
    "return_to_a_phantom_of_truth": "ReturnToAPhantomOfTruth",
    "return_to_the_pallid_mask": "ReturnToThePallidMask",
    "return_to_black_stars_rise": "ReturnToBlackStarsRise",
    "return_to_dim_carcosa": "ReturnToDimCarcosa",
    "delusory_evils": "DelusoryEvils",
    "decaying_reality": "DecayingReality",
    "hasturs_envoys": "HastursEnvoys",
    "maddening_delusions": "MaddeningDelusions",
    "neurotic_fear": "NeuroticFear",
    "return_to_the_untamed_wilds": "ReturnToTheUntamedWilds",
    "return_to_the_doom_of_eztli": "ReturnToTheDoomOfEztli",
    "return_to_threads_of_fate": "ReturnToThreadsOfFate",
    "return_to_the_boundary_beyond": "ReturnToTheBoundaryBeyond",
    "return_to_pillars_of_judgment": "ReturnToPillarsOfJudgment",
    "return_to_knyan": "ReturnToKnYan",
    "return_to_the_city_of_archives": "ReturnToTheCityOfArchives",
    "return_to_the_depths_of_yoth": "ReturnToTheDepthsOfYoth",
    "return_to_shattered_aeons": "ReturnToShatteredAeons",
    "return_to_turn_back_time": "ReturnToTurnBackTime",
    "return_to_the_rainforest": "ReturnToTheRainforest",
    "cult_of_pnakotus": "CultOfPnakotus",
    "doomed_expedition": "DoomedExpedition",
    "temporal_hunters": "TemporalHunters",
    "venomous_hate": "VenomousHate",
    "return_to_disappearance_at_the_twilight_estate": "ReturnToDisappearanceAtTheTwilightEstate",
    "return_to_the_witching_hour": "ReturnToTheWitchingHour",
    "return_to_at_deaths_doorstep": "ReturnToAtDeathsDoorstep",
    "return_to_the_secret_name": "ReturnToTheSecretName",
    "return_to_the_wages_of_sin": "ReturnToTheWagesOfSin",
    "return_to_for_the_greater_good": "ReturnToForTheGreaterGood",
    "return_to_union_and_disillusion": "ReturnToUnionAndDisillusion",
    "return_to_in_the_clutches_of_chaos": "ReturnToInTheClutchesOfChaos",
    "return_to_before_the_black_throne": "ReturnToBeforeTheBlackThrone",
    "hexcraft": "Hexcraft",
    "impending_evils": "ImpendingEvils",
    "unspeakable_fate": "UnspeakableFate",
    "unstable_realm": "UnstableRealm",
    "city_of_the_damned": "CityOfTheDamned",
    "chilling_mists": "ChillingMists",
    "bloodthirsty_spirits": "BloodthirstySpirits",
    "bayou": "TheBayou",
    "rougarou": "CurseOfTheRougarouE",
    "venice": "CarnevaleOfHorrorsE",
    "in_the_labyrinths_of_lunacy": "LabyrinthsOfLunacyE",
    "single_group": "SingleGroup",
    "epic_multiplayer": "EpicMultiplayer",
    "the_eternal_slumber": "TheEternalSlumber",
    "the_nights_usurper": "TheNightsUsurper",
    "brotherhood_of_the_beast": "BrotherhoodOfTheBeast",
    "sands_of_egypt": "SandsOfEgypt",
    "abyssal_tribute": "AbyssalTribute",
    "abyssal_gifts": "AbyssalGifts",
    "murder_at_the_excelsior_hotel": "MurderAtTheExcelsiorHotelE",
    "alien_interference": "AlienInterference",
    "excelsior_management": "ExcelsiorManagement",
    "dark_rituals": "DarkRituals",
    "vile_experiments": "VileExperiments",
    "sins_of_the_past": "SinsOfThePast",
    "blob": "TheBlobThatAteEverythingE",
    "blob_epic_multiplayer": "EpicMultiplayer",
    "blob_single_group": "SingleGroup",
    "migo_incursion": "MiGoIncursion",
    "war_of_the_outer_gods": "WarOfTheOuterGodsE",
    "death_of_stars": "DeathOfStars",
    "children_of_paradise": "ChildrenOfParadise",
    "swarm_of_assimilation": "SwarmOfAssimilation",
    "read_or_die": "ReadOrDie",
    "all_or_nothing": "AllOrNothing",
    "bad_blood": "BadBlood",
    "by_the_book": "ByTheBook",
    "red_tide_rising": "RedTideRising",
    None: "",
}
SPECIAL_ENCOUNTER_CARDS = [
    "03276a",
    "03279b",
    "03297",
    "03298",
    "03276b",
    "03279a",
    "03296",
    "03299",
]
PACK_CODES_TO_NAMES = {
    "core": "CoreSet",
    "rcore": "CoreSet",
    "dwl": "TheDunwichLegacy",
    "tmm": "TheDunwichLegacy",
    "tece": "TheDunwichLegacy",
    "bota": "TheDunwichLegacy",
    "uau": "TheDunwichLegacy",
    "wda": "TheDunwichLegacy",
    "litas": "TheDunwichLegacy",
    "ptc": "ThePathToCarcosa",
    "eotp": "ThePathToCarcosa",
    "tuo": "ThePathToCarcosa",
    "apot": "ThePathToCarcosa",
    "tpm": "ThePathToCarcosa",
    "bsr": "ThePathToCarcosa",
    "dca": "ThePathToCarcosa",
    "tfa": "TheForgottenAge",
    "tof": "TheForgottenAge",
    "tbb": "TheForgottenAge",
    "hote": "TheForgottenAge",
    "tcoa": "TheForgottenAge",
    "tdoy": "TheForgottenAge",
    "sha": "TheForgottenAge",
    "tcu": "TheCircleUndone",
    "tsn": "TheCircleUndone",
    "wos": "TheCircleUndone",
    "fgg": "TheCircleUndone",
    "uad": "TheCircleUndone",
    "icc": "TheCircleUndone",
    "bbt": "TheCircleUndone",
    "tde": "TheDreamEaters",
    "sfk": "TheDreamEaters",
    "tsh": "TheDreamEaters",
    "dsm": "TheDreamEaters",
    "pnr": "TheDreamEaters",
    "wgd": "TheDreamEaters",
    "woc": "TheDreamEaters",
    "tic": "TheInnsmouthConspiracy",
    "itd": "TheInnsmouthConspiracy",
    "def": "TheInnsmouthConspiracy",
    "hhg": "TheInnsmouthConspiracy",
    "lif": "TheInnsmouthConspiracy",
    "lod": "TheInnsmouthConspiracy",
    "itm": "TheInnsmouthConspiracy",
    "eoep": "EdgeOfTheEarthInv",
    "eoec": "EdgeOfTheEarth",
    "rtnotz": "ReturnToTheNightOfTheZealot",
    "rtdwl": "ReturnToTheDunwichLegacy",
    "rtptc": "ReturnToThePathToCarcosa",
    "rttfa": "ReturnToTheForgottenAge",
    "rttcu": "ReturnToTheCircleUndone",
    "cotr": "CurseOfTheRougarou",
    "coh": "CarnevaleOfHorrors",
    "lol": "LabyrinthsOfLunacy",
    "guardians": "GuardiansOfTheAbyss",
    "hotel": "MurderAtTheExcelsiorHotel",
    "blob": "TheBlobThatAteEverything",
    "wog": "WarOfTheOuterGods",
    "nat": "NathanielCho",
    "har": "HarveyWalters",
    "win": "WinifredHabbamock",
    "jac": "JacquelineFine",
    "ste": "StellaClark",
    "rod": "ParallelInvestigators",
    "aon": "ParallelInvestigators",
    "bad": "ParallelInvestigators",
    "btb": "ParallelInvestigators",
    "rtr": "ParallelInvestigators",
    "hoth": "Promos",
    "tdor": "Promos",
    "iotv": "Promos",
    "tdg": "Promos",
    "tftbw": "Promos",
    "bob": "Promos",
    "dre": "Promos",
}
SE_ACT_BACK_CODES = [
    "03322a",
    "03323a",
    "04048",
    "04049",
    "04318",
    "06292",
    "06337",
]
SE_ACT_FRONT_CODES = ["08681"]
SE_AGENDA_BACK_CODES = ["01145", "02314", "05199"]
SE_AGENDA_FRONT_CODES = [
    "84043",
    "84044",
    "84045",
    "84046",
    "84047",
    "84048",
    "84049",
    "84050",
    "84051",
    "84052",
    "86034",
    "86040",
    "86046",
]
ADB_X_VALUE = "X"
ADB_STAR_HEALTH = "Star"
ADB_VAR_HEALTH = -2
LOCATION_ICON_MAP = {
    LocationIcon.TILDE: LocationIcon.SLASH,
    LocationIcon.SQUARE: LocationIcon.SQUARE,
    LocationIcon.PLUS: LocationIcon.CROSS,
    LocationIcon.CIRCLE: LocationIcon.CIRCLE,
    LocationIcon.TRIANGLE: LocationIcon.TRIANGLE,
    LocationIcon.DIAMOND: LocationIcon.DIAMOND,
    LocationIcon.CRESCENT: LocationIcon.MOON,
    LocationIcon.TEE: LocationIcon.T,
    LocationIcon.APOSTROPHE: LocationIcon.QUOTE,
    LocationIcon.CLOVER: LocationIcon.CLOVER,
    LocationIcon.STAR: LocationIcon.STAR,
    LocationIcon.HEART: LocationIcon.HEART,
    LocationIcon.SPADE: LocationIcon.SPADE,
    LocationIcon.HOURGLASS: LocationIcon.HOURGLASS
}

SE_ENCOUNTER_BACK_VISIBILITY_CODES = [
    "07048",
    "07049",
    "07050",
    "07051",
    "07052",
    "07102",
    "07103",
    "07104",
    "07174a",
    "07174b",
    "07247",
    "07248",
    "07249",
    "07250",
    "07251",
    "07290",
    "07319",
]
DECKS_FOLDER_NAME = "decks"
CARDS_FOLDER_NAME = "cards"
AHDB_FOLDER_NAME = "ahdb"
DATA_DIR_NAME = "SE_Generator/data"
TRANSLATIONS_DIR_NAME = "translations"
CACHE_DIR_NAME = "cache"
REPOS_DIR_NAME = "repos"
DOOM_COMMENT_CARD_CODE = "04212"
REVERSED_CARD_CODES = [
    "03182b",
    "03221b",
    "03325b",
    "03326b",
    "03326d",
    "03327b",
    "03327d",
    "03327f",
    "03328b",
    "03328d",
    "03328f",
    "03329b",
    "03329d",
    "03330b",
    "03331b",
    "04325b",
    "04326b",
    "05085b",
    "05166",
    "05167",
    "05168",
    "05169",
    "05170",
    "05171",
    "05172",
    "05173",
    "05174",
    "05175",
    "05176",
    "05217",
    "05262",
    "05263",
    "05264",
    "05265",
    "07252",
    "51026b",
    "82017",
    "82018",
    "82019",
    "82020",
    "83022b",
    "83023b",
    "83024b",
    "83025b",
    "83026b",
]
PROCESS_STEPS = ["translate", "generate", "pack", "upload", "update"]
HTML_PARSER = "html.parser"
DECKS_FOLDER_NAME = "decks"
CARDS_FOLDER_NAME = "cards"
AHDB_FOLDER_NAME = "ahdb"
DATA_DIR_NAME = "SE_Generator/data"
TRANSLATIONS_DIR_NAME = "translations"
CACHE_DIR_NAME = "cache"
REPOS_DIR_NAME = "repos"
DOOM_COMMENT_CARD_CODE = "04212"
REVERSED_CARD_CODES = [
    "03182b",
    "03221b",
    "03325b",
    "03326b",
    "03326d",
    "03327b",
    "03327d",
    "03327f",
    "03328b",
    "03328d",
    "03328f",
    "03329b",
    "03329d",
    "03330b",
    "03331b",
    "04325b",
    "04326b",
    "05085b",
    "05166",
    "05167",
    "05168",
    "05169",
    "05170",
    "05171",
    "05172",
    "05173",
    "05174",
    "05175",
    "05176",
    "05217",
    "05262",
    "05263",
    "05264",
    "05265",
    "07252",
    "51026b",
    "82017",
    "82018",
    "82019",
    "82020",
    "83022b",
    "83023b",
    "83024b",
    "83025b",
    "83026b",
]
